[tool.poetry]
name = "apro"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
gloro = { path = "./gloro/" }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
